language: en-US

early_access: true
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai 요약'
  auto_title_placeholder: '@coderabbitai'
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/README.md"
    - "!**/*.js"
  path_instructions:
    - path: "**/*.kt"
      instructions: >
        You are a senior Kotlin & Spring backend developer and a global software engineer.  
        1. Review this code from a Senior Kotlin + Spring perspective: focus on architecture, object-oriented design, clean code principles, and idiomatic “Kotlin-style” usage (e.g., data classes, extension functions, null-safety, coroutines).  
        2. As a global developer, also critique my English: check grammar, phrasing, clarity, and overall writing quality in any comments or documentation.  
        3. Provide actionable suggestions and examples where improvements are needed, highlighting high-severity issues clearly.  
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: [ ]
    labels: [ ]
    drafts: false
    base_branches: [ ]
  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      disabled_rules:
        - EN_UNPAIRED_BRACKETS
        - EN_UNPAIRED_QUOTES
      disabled_categories:
        - TYPOS
        - TYPOGRAPHY
        - CASING
      enabled_only: false
      level: default
      enabled_rules: [ ]
      enabled_categories: [ ]
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    ast-grep:
      packages: [ ]
      rule_dirs: [ ]
      util_dirs: [ ]
      essential_rules: true
chat:
  auto_reply: true
knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: [ ]
  linear:
    team_keys: [ ]